#!/bin/bash
# ssh-tunnel

# $1: url
# $2: port
# $3: remote port

key_path=/path/to_key/id_rsa_mmonge

user=
host=

echo -e "Tunneling to $1:$3, use port: $2 \n"
ssh -L $2:$1:$3 $user@$host -i $key_path